name: Mend UA MultiOrg Scan

on:
  push:
     branches:
     - v10/contrib
     - v9/contrib
     - v8/dev
     - '**feature/**'
     - '**bugfix/**'

jobs:
  mendscan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    #- name: Build DotNET projects
    #  run: dotnet build umbraco.sln --configuration Release
    - name: Mend Unified Agent Production Org Scan
      if: github.ref_name == 'v10/contrib' || 
        github.ref_name == 'v9/contrib' ||
        github.ref_name == 'v8/dev'
      env:
        WS_APIKEY: ${{secrets.PROD_APIKEY}}
        WS_USERKEY: ${{secrets.PROD_USERKEY}}
        WS_WSS_URL: https://saas.mend.io/agent
        WS_PRODUCTNAME: ${{github.event.repository.name}}_${{github.ref_name}}
        WS_PROJECTPERFOLDER: true
        WS_GENERATEPROJECTDETAILSJSON: true
      run: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        java -jar wss-unified-agent.jar -d ./src
    - name: Mend Unified Agent Development Org Scan
      if: contains(github.ref_name, 'feature') ||
        contains(github.ref_name, 'bugfix')
      env:
        WS_APIKEY: ${{secrets.DEV_APIKEY}}
        WS_USERKEY: ${{secrets.DEV_USERKEY}}
        WS_WSS_URL: https://saas.mend.io/agent
        WS_PRODUCTNAME: ${{github.event.repository.name}}_${{github.ref_name}}
        WS_PROJECTPERFOLDER: true
        WS_GENERATEPROJECTDETAILSJSON: true
      run: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        java -jar wss-unified-agent.jar -d ./src
