name: Mend UA MultiOrg Scan

on:
  push:
    branches:
    - v10/contrib
    - v9/contrib
    - v8/dev


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Build DotNET projects
      run: dotnet build umbraco.sln
    - name: WhiteSource Unified Agent Scan
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        WS_APIKEY: ${{secrets.PROD_APIKEY}}
        WS_USERKEY: ${{secrets.PROD_USERKEY}}
        WS_WSS_URL: https://saas.mend.io/agent
        WS_PRODUCTNAME: ${{github.event.repository.name}}_${{github.ref_name}}
        WS_PROJECTPERFOLDER: true
        WS_GENERATEPROJECTDETAILSJSON: true
      run: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        java -jar wss-unified-agent.jar
        